- id: 1
  key: renminbi
  code: inr
  symbol: "₹"
  coin: false
  precision: 2
  assets:
    accounts:
      -
        bank: 'State Bank of India'
        address: '6225 0885 6022 3501'
        password: '111111'
        tel: '95555'
- id: 2
  key: satoshi
  code: btc
  symbol: "฿"
  coin: true
  quick_withdraw_max: 0
  rpc: http://coinrootsbtc:9YGfDb+j*yFJ@127.0.0.1:18332
  blockchain: https://blockchain.info/tx/#{txid}
  address_url: https://blockchain.info/address/#{address}
  assets:
    accounts:
      -
        address: 16Jzdt5L7UnSyeNjVmAxCtUgVDo8iJrvVJ
- id: 3
  key: avon
  code: acn
  symbol: "ACN"
  coin: true
  quick_withdraw_max: 0
  rpc: http://coinrootsacn:xrwanZ&V+2K=@127.0.0.1:18332
  blockchain: https://avoncoin.info/tx/#{txid}
  address_url: https://avoncoin.info/address/#{address}
  assets:
    accounts:
      -
        address: NTCmqwgSgdF3DpiANAdgsWei6NpNAXibvw
- id: 4
  key: opera
  code: opc
  symbol: "OPC"
  coin: true
  quick_withdraw_max: 0
  rpc: http://coinrootsopc:a@&Pu5Ey!VMm@127.0.0.1:18332
  blockchain: https://operacoin.info/tx/#{txid}
  address_url: https://operacoin.info/address/#{address}
  assets:
    accounts:
      -
        address: SacRAAVAM2hPBsyt5YeFWctVXukNwVV6pL
