development: &defaults
  adapter: mysql2
  encoding: utf8
  database: coinroots_development
  username: root
  password: coinroots
  pool: 10
  reconnect: true

test:
  <<: *defaults
  database: coinroots_test

production:
  <<: *defaults
  database: coinroots_production
